name: Build

on:
  push:
    branches:
      - development

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'

      - name: Cache Desktop node_modules
        id: cache-desktop-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock', 'patches/**') }}

      - name: Install Desktop node_modules
        if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: build artifacts for windows
        run: |
          yarn generate
          node build\grunt.js
          copy package.json temp.json
          type temp.json | findstr /v certificateSubjectName | findstr /v certificateSha1 > package.json
          yarn prepare-beta-build
          yarn build
        env:
          NODE_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup artifacts for windows
        run:
          npx rimraf "release/!(*.exe)"

      - name: Release package
        run:
          yarn publish:win:setup

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
